[project]
name = "cypher-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets==4.8.*",
    "pydantic-settings",
    "trl[vllm]==1.6.*",
    "peft",
    "bitsandbytes",
    "pillow",
    "torch==2.10.*",
    "torchvision",
    "torchaudio",
    "langchain",
    "trackio[gpu]==0.26.*",
    "transformers>=5.5.*",
    "cypherbench",
    "torchao==0.16.*",
    "types-tqdm>=4.68.0.20260608",
]

[tool.uv]
override-dependencies = ["vllm==0.19.1"]

[tool.uv.sources]
cypherbench = { git = "https://github.com/VikramRangarajan/cypherbench.git" }
torch = [
    { index = "pytorch-cu129" },
]
torchvision = [
    { index = "pytorch-cu129" },
]
torchaudio = [
    { index = "pytorch-cu129" },
]
vllm = [
    { index = "vllm-cu129" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[[tool.uv.index]]
name = "vllm-cu129"
url = "https://wheels.vllm.ai/0.19.1/cu129/"
explicit = true

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[dependency-groups]
dev = [
    "pyrefly>=1.0.0",
    "ruff>=0.9.10",
]
