[project]
name = "cypher-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets==4.8.*",
    "pydantic-settings",
    "trl==1.5.*",
    "peft",
    "bitsandbytes",
    "pillow",
    "torch",
    "torchvision",
    "langchain",
    "trackio[gpu]==0.26.*",
    "transformers==5.10.*",
    "cypherbench",
    "torchao==0.17.*",
]

[tool.uv.sources]
cypherbench = { git = "https://github.com/VikramRangarajan/cypherbench.git" }
torch = [
    { index = "pytorch-cu129" },
]
torchvision = [
    { index = "pytorch-cu129" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
project-excludes = ["grpo.py"]

[dependency-groups]
dev = [
    "pyrefly>=1.0.0",
    "ruff>=0.9.10",
]

[tool.ruff]
extend-exclude = [
    "grpo.py",
    "train.py",
    "eval.py",
]